config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'teaples' => 'teaples#index'

  resources :teaples do
    resources :messages
  end

  root 'teaples#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :teaple

end

app/models/teaple.rb
class Teaple < ActiveRecord::Base

  has_many :messages
  belongs_to :user

  geocoded_by :postcode
  after_validation :geocode

  def No_Of_Messages
    return "(" + Message.where(teaple_id: self.id).count.to_s + ")"
  end

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :teaples
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    #this @teaple is lost when the page is rendered?
    @teaple = Teaple.find(params[:teaple_id])
    @message = Message.new
  end

  def create
    @teaple = Teaple.find(params[:teaple_id])
    @teaple.messages.create(message_params)
    flash[:notice] = "Thanks for sending a message to #{@teaple.name}!"
    if !current_user
      redirect_to teaples_path()
    elsif current_user.id == @teaple.user_id
      redirect_to teaple_messages_path(@teaple)
    else
      redirect_to teaples_path()
    end
  end

  def message_params
    params.require(:message).permit(:messageText)
  end

  def index
    @teaple = Teaple.find(params[:teaple_id])
    if user_signed_in?
      if current_user.id == @teaple.user_id
        @messages = Message.where(teaple_id: @teaple.id).find_each
      else
        flash[:notice] = "You must be logged in as the user who created the teaple to see their messages"
        redirect_to '/'
      end
    else
      flash[:notice] = "You must be logged in to see Teaple messages"
      redirect_to '/'
    end
  end

end

app/controllers/teaples_controller.rb
class TeaplesController < ApplicationController

  def index
#    @teaples = Teaple.all
    @teaples = Teaple.paginate(:page => params[:page], :per_page =>5 )
  end

  def new
    @teaple = Teaple.new
  end

  def show
    @teaple = Teaple.find(params[:id])
    @creator = User.find(@teaple.user_id).email
  end

  def create
    if current_user
      @teaple = Teaple.create(teaple_params.merge({user_id:current_user.id}))
      flash[:notice] = "Thanks for signing up, #{@teaple.name}!"
    else
      flash[:notice] = "Only logged in users can sign up Teaple"
    end
    redirect_to '/'
  end

  def teaple_params
    params.require(:teaple).permit(:name, :bio, :location, :postcode, :image)
  end

end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/teaples_helper.rb
module TeaplesHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teaple</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
  <h1>Teaple</h1>
  <%= link_to "Home", teaples_path() %> <br>
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%= yield %>

</div>
</body>
</html>

app/views/messages/index.html.erb
Here are <%= "#{ @teaple.name }'s" %> messages:

<ul>
  <% if @messages %>
    <% @messages.each do |message|%>
      <li>
      <%= "#{message.messageText}" %>
      </li>
    <%  end %>
  <%  end %>
</ul>

app/views/messages/new.html.erb
Please fill in the form below letting <% "#{ @teaple.name }" %> you'd like to meet:
<%= form_for [@teaple, @message] do |f| %>
  <%= f.label :messageText %>
  <%= f.text_field :messageText %>
  <%= f.submit "Arrange Meeting" %>
<% end %>

app/views/teaples/index.html.erb
<section id="main">

<% if @teaples.any? %>
Here is the list of teaples you can arrange to meet:
  <ul>
    <% @teaples.each do |teaple|%>
      <li><%= link_to teaple.name, teaple_path(teaple) %>
          <%=link_to teaple.No_Of_Messages, teaple_messages_path(teaple) %>
          <%= link_to "Arrange meeting", new_teaple_message_path(teaple) %> </li>
    <%  end %>
  </ul>
  <%= will_paginate @teaples %>
<% else %>
  <h2>No teaples added yet</h2>
<% end %>

<%= link_to "Add your profile", new_teaple_path %> <br>


<% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
<% end %>

</section>

app/views/teaples/js/_gmaps.js.erb
var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'geolocation'} }, function(){
  var marker = handler.addMarker({


    "lat": <%= @teaple.latitude %>,
    "lng": <%= @teaple.longitude %>
  });
  handler.map.centerOn(marker);
});

app/views/teaples/new.html.erb
<%= form_for @teaple, html: {multipart: true} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br/><br/>
  <%= f.label :bio %>
  <%= f.text_field :bio %><br/><br/>
  <%= f.label :location %>
  <%= f.text_field :location %><br/><br/>
  <%= f.label :postcode %>
  <%= f.text_field :postcode %><br/><br/>
  <%= f.file_field :image %> <br>
  <%= f.submit "Save profile" %>
<!--   <%= f.file_field :image %> -->
<% end %>

app/views/teaples/show.html.erb
<section id="profile">
  <h3><span class="prof">Name:</span> <%= @teaple.name %></h3>
  <p><span class="prof">Bio:</span> <%= @teaple.bio %></p>
  <p><span class="prof">Location:</span> <%= @teaple.location %></p>

  <% if @teaple.image_file_name %>
    <p> <%= image_tag @teaple.image.url(:thumb) %></p>
  <% end %>

  <p><span class="prof">Created by:</span> <%= @creator %></p>
  <p><span class="prof">Long/Lat:</span> <%= "#{@teaple.latitude}, #{@teaple.longitude}" %></p>

  <div>
    <% if @teaple.postcode.length != 0 %>
      <div id="geolocation" style="width: 100%; height: 400px; border:3px solid #999;border-radius:10px;
            box-shadow:1px 2px 7px rgba(0,0,0,.3);">
      </div>
    <% end %>
  </div>


  <br/>
  <p><a class="button" href="/teaples">Back to home page</a></p>

</section>

<script>
  <%= render partial: 'teaples/js/gmaps', formats: [:js] %>
</script>